#! /bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

sudo ln -s $SCRIPT_DIR/gfkl /usr/share/X11/xkb/symbols/gfkl
sudo ln -s $SCRIPT_DIR/wokmok /usr/share/X11/xkb/symbols/wokmok
sudo ln -s $SCRIPT_DIR/layer5 /usr/share/X11/xkb/symbols/layer5
