#!/bin/sh

chosen=""

while getopts ":wud" opt; do
    case $opt in
        w) chosen="wokmok";;
        u) chosen="us";;
        d) chosen="danish";;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

if [[ $# -eq 0 ]] ; then
    echo "Usage: -w for wokmok, -u for us intl., -d for danish"
    exit 0
fi

killall -q xcape

case "$chosen" in
    "wokmok") 
        setxkbmap -layout gfkl -model pc105
        # xcape -e '#66=Escape;#23=Tab;#36=Return;#64=F12' -t 180
        xcape -e '#66=Escape;#36=Return;#64=F12' -t 180
        # xcape -e '#65=space' -t 180
        # xcape -e '#40=r;#46=e' -t 180;;
        xcape -e '#94=x' -t 180
        xcape -e '#62=slash' -t 180;;
    "us")
        setxkbmap -layout us -variant altgr-intl -model pc105 -option altwin:swap_lalt_lwin
        xcape -e '#64=F12' -t 180;;
    "danish")
        setxkbmap -layout dk -model pc105 -option altwin:swap_lalt_lwin
        xcape -e '#64=F12' -t 180;;
esac
